Здравствуйте!
pydotplus установил, при вводе команды вылетает ошибка:
pydotplus.graphviz.InvocationException: GraphViz's executables not found
Установил отдельно graphviz - та же ошибка

Установил debug-toolbar.
Все сделал как вы. Команда : python manage.py runserver 0.0.0.0:8000
Сервер запустился но не открывается: "Не получается получить доступ к сайту".
Все обучение приходиться бороться с виндой. Понимаю теперь почему нужен линукс.

